# antora generate playbook-local.yml
# antora generate --to-dir local playbook-local.yml
# antora generate --clean --to-dir local playbook-local.yml
runtime:
  cache_dir: ./.cache/antora
  fetch: true
site:
  title: 安宁的博客
  url: https://peacetrue.cn/summarize/index.html
  start_page: sample-security::index.adoc
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml@'
    numbered: '@'
    sectnums: 'all@'
    sectnumlevels: '5@'
    sourcedir: 'src/main/java@'
    testsourcedir: 'src/test/java@'
content:
  branches: master
  sources:
    - url: ../sample-security
#      branches: dev/1.3.0/idaas-jwt-web
      start_path: docs/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./local
  clean: true
#  destinations:
#    - provider: archive
