# antora generate playbook.yml
# antora generate --to-dir public playbook.yml
# antora generate --clean --to-dir public playbook.yml
runtime:
  cache_dir: ./.cache/antora
  fetch: true
site:
  title: 安宁的博客
  url: https://peacetrue.cn/summarize/index.html
  start_page: sample-security::index.adoc
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml@'
    numbered: '@'
    sectnums: 'all@'
    sectnumlevels: '5@'
    sourcedir: 'src/main/java@'
    testsourcedir: 'src/test/java@'
content:
  branches: master
  sources:
    - url: git@github.com:peacetrue/sample-security
      branches: master
      start_path: docs/antora
    - url: git@github.com:peacetrue/learn-spring
      branches: master
      start_path: docs/antora
    - url: git@github.com:peacetrue/peacetrue-microservice-template
      branches: master,dev/1.5.0/spring-authorization-server
      start_path: docs/antora
    - url: git@github.com:peacetrue/learn-reactive
      branches: master
      start_path: docs/antora
    - url: git@github.com:peacetrue/sample-lock
      branches: master
      start_path: docs/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./public
#  clean: true
#  destinations:
#    - provider: archive
