# antora generate playbook.yml
# antora generate --to-dir public playbook.yml
# antora generate --to-dir public playbook.yml --fetch
# antora generate --clean --to-dir public playbook.yml
git:
  fetch_concurrency: 1
runtime:
  cache_dir: ./.cache/antora
  fetch: false
site:
  title: 安宁的博客
  url: https://peacetrue.cn/summarize/index.html
  start_page: peacetrue-result::index.adoc
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml@'
    numbered: '@'
    sectnums: 'all@'
    sectnumlevels: '5@'
    sourcedir: 'src/main/java@'
    testsourcedir: 'src/test/java@'
    path: 'example$project'
    source: 'source'
content:
  branches: master
  sources:
    - url: git@github.com:peacetrue/peacetrue-result
      branches: master
      start_path: docs/antora
    - url: git@github.com:peacetrue/peacetrue-cryptography
      start_path: docs/antora
    - url: git@github.com:peacetrue/peacetrue-beans
      start_path: docs/antora
    - url: git@github.com:peacetrue/peacetrue-validation
      start_path: docs/antora
    - url: git@github.com:peacetrue/peacetrue-spring
      branches: master
      start_path: docs/antora
    - url: git@github.com:peacetrue/sample-sso-oidc
      branches: 1.0.0/basic, 1.1.0/env
      start_path: docs/antora
    - url: git@github.com:peacetrue/learn-spring
      branches: master
      start_path: docs/antora
    - url: git@github.com:peacetrue/peacetrue-microservice-template
      branches: master,dev/1.5.0/spring-authorization-server
      start_path: docs/antora
    - url: git@github.com:peacetrue/learn-reactive
      branches: master
      start_path: docs/antora
    - url: git@github.com:peacetrue/sample-lock
      branches: master
      start_path: docs/antora
#    - url: git@github.com:peacetrue/author
#      branches: master
#      start_path: docs/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./public
#  clean: true
#  destinations:
#    - provider: archive
